FROM node:24-alpine AS frontend_builder

ARG NEXT_PUBLIC_WEBSOCKET_URL
ENV NEXT_PUBLIC_WEBSOCKET_URL=$NEXT_PUBLIC_WEBSOCKET_URL

RUN mkdir /app
WORKDIR /app

ADD ./frontend/package.json ./

RUN npm install;

ADD ./frontend .

RUN npm run build;

EXPOSE 3000
CMD ["npm", "run", "start"]

