FROM node:22-alpine AS frontend_builder

RUN mkdir /app
WORKDIR /app

ADD ./frontend/package.json ./
ADD ./frontend/package-lock.json ./

RUN npm install;

ADD ./frontend .

RUN npm run build;

FROM nginx:alpine AS router

RUN mkdir -p /var/www/veridash/
COPY --from=frontend_builder /app/out/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

